<?php
// $Id: simple_contest_uc_coupon.module,v 1.1.2.2 2010/07/09 04:36:13 4vinoth Exp $
/**
 * @file
 * 
 * simple_contest_uc_coupon module
 */
 
/**
 * Implementation of hook_help
 */
function simple_contest_uc_coupon_help($path, $arg) {
  switch ($path) {
    case 'admin/help#simple_contest_uc_coupon':
      $output = '<p>'. t('provides simple contest integration with Ubercart Coupon module') .'</p>';
      return $output;
  }
}

/*
 * Implementation of hook_simple_contest()
 *
 */
function simple_contest_uc_coupon_simple_contest(&$node, $op,  $a3){
	if($op == 'completed' && $a3){
		$winners = $a3;
		$settings = simple_contest_get_settings($node->type);
		//if ($settings['winner_type'] == 'user'){ //
		foreach($new_winners as $uid => $info){
		
			$data = array();
			$data['roles'] = array();
			$data['users'][] = $uid; // only for this user
			$data['terms'] = array();
			$data['skus'] = array();
			$data['products'] = array();
			$data['product_types'] = array();
			$data['negate_terms'] = TRUE;
			$data['negate_products'] = TRUE;
			$data['max_uses_per_user'] = 1;
			$data['wholesale'] = 1;
			
			$cname = 'Prize Coupon for the contest ' . check_plain($node->title);
			$code = 'CCP' . '_' . $node->nid. '_' . $uid . '_' .  date('Y') . date('m') . date('d');
			
			$valid_until = strtotime("+" . $settings['uc_coupon_expire_length'] . " " + $settings['uc_coupon_expire']);
			
			db_query("INSERT INTO {uc_coupons} (name, code, value, type, status, valid_until, max_uses, minimum_order, data, bulk, bulk_seed) VALUES ('%s', '%s', %f, '%s', %d, %d, %d, %d, '%s', %d, '%s')", $cname, $code, floatval($settings['uc_coupon_values']['value_' . $info->weight]), $settings['uc_coupon_type'], 1, $valid_until, 0, 0, serialize($data), 0, md5(uniqid()));
		
		db_query("INSERT INTO {simple_contest_uc_coupon} ('nid', 'uid', 'cid', 'value') VALUES (%d, %d, %d, %f)", $node->nid, $uid, db_last_insert_id('uc_coupons', 'cid'), floatval($settings['uc_coupon_values']['value_' . $info->weight]));
		}
	}
}


/**
 * Implementation of hook_form_alter().
 */
function simple_contest_uc_coupon_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'simple_contest_content_type_settings_form') {
	
		$type = $form_state['type'];  
		$settings = simple_contest_get_settings($type);
		
		$form['simple_contest']['prize_coupons'] = array(
			'#type' => 'fieldset',
			'#title' => t('Prize Coupons'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#description' => t('Ubercart coupons will be created for each winners based on the settings below. Enter values without symbols, for $15, enter "15" and choose Price as the discount type.'),
			'#weight' => 5,
		);
		
		$form['simple_contest']['prize_coupons']['uc_coupon_type'] = array(
			'#type' => 'select',
			'#title' => t('Coupon type'),
			'#default_value' => $settings['uc_coupon_type'],
			'#options' => array(
				'price' => 'Price',
				'percentage' => 'Percentage',				
			),
		);
		
		$form['simple_contest']['prize_coupons']['uc_coupon_values'] = array(
			'#type' => 'fieldset',
			'#title' => t('Prize Coupons'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#weight' => 5,
			'#tree' => TRUE,
		);
		
		for($count = 1; $count <= $settings['max_winners']; $count++){
			$form['simple_contest']['prize_coupons']['uc_coupon_values']['value_' . $count] = array(
				'#type' => 'textfield',
				'#title' => t('coupon value for winner ' . $count),
				'#size' => 30,
				'#default_value' => $settings['uc_coupon_values']['value_' . $count],
				'#required' => TRUE,
				'#weight' => $count,
			);
		}
		$options = array();
		for($i; $i<=31; $i++){
			$options[$i] = $i;
		}
		$form['simple_contest']['prize_coupons']['uc_coupon_expire_length'] = array(
			'#type' => 'textfield',
			'#title' => t('Expire after'),
			'#default_value' => $settings['uc_coupon_expire_length'],
			'#options' => $options,
		);
		$form['simple_contest']['prize_coupons']['uc_coupon_expire'] = array(
			'#type' => 'select',
			'#default_value' => $settings['uc_coupon_expire'],
			'#options' => array(
				'day' => 'Day(s)',
				'week' => 'Week(s)',
				'month' => 'Month(s)',
				'year' => 'Year(s)',
			),
		);
		$form['#submit'][] = '_simple_contest_uc_coupon_content_type_settings_form_submit';
		$form['#validate'][] = '_simple_contest_uc_coupon_content_type_settings_form_validate';

	}
}

function _simple_contest_uc_coupon_content_type_settings_form_validate($form, &$form_state) {
	foreach($form_state['values']['uc_gift_certificates'] as $key => $value){
		if (empty($value) || !is_numeric($value)) {
			form_set_error("simple_contest][uc_gift_certificates][$key", t('Invalid value for ' . $key));
		}
	}
}

function _simple_contest_uc_coupon_content_type_settings_form_submit($form, &$form_state) {

	//$settings = simple_contest_get_settings($form_state['type']);
	
}


/**
 * Implementation of hook_order().
 *
 * Ensure any cart pane coupon is added to the order if the checkout page is skipped
 * (e.g. Paypal Express Checkout, Google Checkout)
 */
function simple_contest_uc_coupon_order($op, &$arg1, $arg2) {
  if ($op == 'save') {
    $res = db_query("SELECT cid, value FROM {uc_coupons_orders} WHERE oid = %d", $arg1->order_id);
		// when to ?
		
  }
}

/**
 * Implementation of hook_simple_contest_settings()
 */
function simple_contest_uc_coupon_simple_contest_settings() {
  return array(
		'uc_coupon_values' => array(),
		'uc_coupon_type' => 'price',
		'uc_coupon_expire_length' => 1,
		'uc_coupon_expire' => 'year',
  );
	
}
