<?php
// $Id: simple_contest_uc_gift_certificate.module,v 1.1.2.2 2010/07/09 04:36:13 4vinoth Exp $
/**
 * @file
 * 
 * simple_contest_uc_gift_certificate module
 */
 
/**
 * Implementation of hook_help
 */
function simple_contest_uc_gift_certificate_help($path, $arg) {
  switch ($path) {
    case 'admin/help#simple_contest_uc_gift_certificate':
      $output = '<p>'. t('provides simple contest integration with Ubercart Gift certificate module') .'</p>';
      return $output;
  }
}

/*
 * Implementation of hook_simple_contest()
 *
 */
function simple_contest_uc_gift_certificate_simple_contest(&$node, $op,  $a3){
	if($op == 'completed' && $a3){
		$new_winners = $a3;
		$settings = simple_contest_get_settings($node->type);
		//if ($settings['winner_type'] == 'user'){ //
		foreach($new_winners as $uid => $info){
			$data = array();
			$data['value'] = floatval($settings['uc_coupon_values']['value_' . $info->weight]);
			$data['user_id'] = $uid;
			$data['purchaser_id'] = 1; // always user 1
			$data['name'] = 'Price Gift for the Contest : ' . check_plain($node->title) ;
			
			
			$form_state['values'] = $data;
			//$form = array();
			
			module_load_include('inc', 'uc_gift_certificate', 'uc_gift_certificate.admin');
			// it redirects to gift cetificate admin page
			//uc_gift_certificate_add_form_submit($form, $form_state);
			
			$do_mail = TRUE;
			
			$cert_code = uc_gift_certificate_mKey();
			
			
			$success = drupal_write_record('uc_gift_certificates', $form_state['values']);
			$certificate_id = db_last_insert_id('uc_gift_certificates', 'certificate_id');
			$cert_code = $certificate_id."-".$cert_code;
			db_query("UPDATE {uc_gift_certificates} SET cert_code = '%s' WHERE certificate_id = %d", $cert_code, $certificate_id);
		

			if ($success) {
				if ($do_mail) {
					$cert = uc_gift_certificate_load($certificate_id);
					$user = user_load(array('uid' => $cert->user_id));
					uc_gift_certificate_mail_cert_notice($user->mail, $certificate_id, $form_state['values']['msg_to_recipient']);
					
				}

			}
			
		}
	}
}


/**
 * Implementation of hook_form_alter().
 */
function simple_contest_uc_gift_certificate_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'simple_contest_content_type_settings_form') {
	
		$type = $form_state['type'];  
		$settings = simple_contest_get_settings($type);
		
		$form['simple_contest']['uc_gift_certificates'] = array(
			'#type' => 'fieldset',
			'#title' => t('Prize Gift Certificates'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#description' => t('Ubercart gift certificates will be created for each winners based on the settings below.'),
			'#weight' => 5,
			'#tree' => TRUE,
		);
		
		for($count = 1; $count <= $settings['max_winners']; $count++){
			$form['simple_contest']['uc_gift_certificates']['value_' . $count] = array(
				'#type' => 'textfield',
				'#title' => t('Gift certificates value for winner ' . $count),
				'#size' => 30,
				'#default_value' => $settings['uc_gift_certificates']['value_' . $count],
				'#required' => TRUE,
				'#weight' => $count,
			);
		}
		
		$form['#submit'][] = '_simple_contest_uc_gift_certificate_content_type_settings_form_submit';
		$form['#validate'][] = '_simple_contest_uc_gift_certificate_content_type_settings_form_validate';

	}
}

function _simple_contest_uc_gift_certificate_content_type_settings_form_validate($form, &$form_state) {
	foreach($form_state['values']['uc_gift_certificates'] as $key => $value){
		if (empty($value) || !is_numeric($value)) {
			form_set_error("simple_contest][uc_gift_certificates][$key", t('Invalid value for ' . $key));
		}
	}
}

function _simple_contest_uc_gift_certificate_content_type_settings_form_submit($form, &$form_state) {

	//$settings = simple_contest_get_settings($form_state['type']);
	
}


/**
 * Implementation of hook_simple_contest_settings()
 */
function simple_contest_uc_gift_certificate_simple_contest_settings() {
  return array(
		'uc_gift_certificates' => array(),
  );
	
}
